/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.tcs.tallerListas;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

import com.tcs.tallerListas.beans.Estudiante;


public class IngresoEstudiantes {
	

	static ArrayList<Estudiante> arrayEst = new ArrayList<Estudiante>();
	static List<Estudiante> listJar = new ArrayList<Estudiante>();
	static List<Estudiante> listPri = new ArrayList<Estudiante>(); 
	static List<Estudiante> listSeg = new ArrayList<Estudiante>(); 
	static List<Estudiante> listTer = new ArrayList<Estudiante>(); 
	static List<Estudiante> listCua = new ArrayList<Estudiante>(); 
	static List<Estudiante> listQui = new ArrayList<Estudiante>(); 


	public static void main(String[] args) {
		
		Integer contarEst=0;
		String[] estData = null;
		ArrayList<Estudiante> arrayEst = new ArrayList<Estudiante>(); 
		String wGrado = null;
		
		System.out.println("################ Ingreso de estudiantes ################");
		
		try {
			Scanner data = new Scanner(new File("src/main/resources/data.txt"));
			
			while (data.hasNextLine()) {
				estData = data.nextLine().split(",");
				
				Estudiante westudi = new Estudiante();
				 
				westudi.setNroId(estData[0]);
				westudi.setNombre(estData[1]);
				try {
					westudi.setEdad(Integer.parseInt(estData[2]));
					if (westudi.getEdad()>= 6 && westudi.getEdad() <= 10 ) {
						contarEst++;			
					}
				}
				catch (NumberFormatException e) {
					// TODO: handle exception
					System.out.println("La edad no es valida..." +e.getMessage()+"\n");
					e.printStackTrace();
				}
				
				westudi.setEstado(estData[3]);
				westudi.setGrado(estData[4]);
				
				switch (estData[4]) {
				case "Jardin":
					listJar.add(westudi);
					break;
				case "Primero":
					listPri.add(westudi);
					break;
				case "Segundo":
					listSeg.add(westudi);
					break;
				case "Tercero":
					wGrado = estData[4];
					listTer.add(westudi);
					break;
				case "Cuarto":
					wGrado = estData[4];
					listCua.add(westudi);
					break;
				case "Quinto":
					wGrado = estData[4];
					listQui.add(westudi);
					break;
				default:
					break;
				}
				arrayEst.add(westudi);
			} 
			data.close();
			
		} catch (FileNotFoundException e) {
			System.out.println("El archivo no fue encontrado..." +e.getMessage());
			e.printStackTrace();
		}
		System.out.print("El total de estudiantes registrados es de: "+arrayEst.size()+"\n");
		System.out.print("El total de estudiantes entre 6 y 10 años son: "+contarEst+"\n "+"\n ");
		
		MostrarGrados(listJar,"Jardin");
		MostrarGrados(listPri,"Primero");
		MostrarGrados(listSeg,"Segundo");
		MostrarGrados(listTer,"Tercero");
		MostrarGrados(listCua,"Cuarto");
		MostrarGrados(listQui,"Quinto");
		
		System.out.println("\n"+"Los estudiante con Tarjeta de Identidad son: "+"\n");
		for (int i=0; i<arrayEst.size();i++) {
			Estudiante infoest = arrayEst.get(i);
			
			String tipoId =infoest.getNroId().substring( 0,2);
			if (tipoId.equals("TI")) { 
				System.out.print(infoest.getNombre()+" tiene "+infoest.getEdad()+" Años y esta en el grado "+infoest.getGrado()+"\n");
			} 
			//if (infoest.getEstado().equals("Si")) {
				
				//System.out.print(infoest.getNombre()+"\n ");
			//}
		}
		
		System.out.println("\n"+"Los siguientes estudiantes son los que deben repetir el año: "+"\n");
		for (int i=0; i<arrayEst.size();i++) {
			if (arrayEst.get(i).getEstado().equals("Si")) {
				System.out.println(arrayEst.get(i).getNombre()+"del grado "+arrayEst.get(i).getGrado());
			}
		}

	}
	public static void MostrarGrados(List<Estudiante> arrayList, String wGrado) {
		System.out.println("\n"+"Los estudiantes del grado " +wGrado + " son: ");
		for (int i=0; i<arrayList.size();i++) {
			
			System.out.println("Identificación: "+arrayList.get(i).getNroId());
			System.out.println("Nombre: "+arrayList.get(i).getNombre());
			System.out.println("Edad: "+arrayList.get(i).getEdad());
			System.out.println("Grado: "+arrayList.get(i).getGrado());
			System.out.println("Aprobo: "+arrayList.get(i).getEstado());
		}
	}
}